### ISSUE TITLE
Python crash

### ISSUE THREAD

**Issue by leornt** [u1234x1234/youtube-sync#3]
Recently my sync stopped for no reason, so I restarted the container and when it came up I got the logs, after some time it returned me the following error

```
youtubeSync    | 2022-11-28T22:28:02.573634915Z 
youtubeSync    | 2022-11-28T22:28:02.573637595Z 2022-11-28 22:28:02.571 DEBUG youtube_sync.download Command to execute: [['yt-dlp', '--continue', '--ignore-errors', '--rm-cache-dir', '--socket-timeout', '10', '--download-archive', '/downloads/SHAY/downloaded.txt', '-o', '/downloads/SHAY/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PL-1j3ZZT-LGc9h4v3XQif90l0H5fwGHxH', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0']]
youtubeSync    | 2022-11-28T22:28:04.174176419Z WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
youtubeSync    | 2022-11-28T22:28:04.754899562Z WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
youtubeSync    | 2022-11-28T22:28:28.973039358Z ERROR: [youtube] 9PtMdFmJaD8: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:29.840294508Z ERROR: [youtube] 5_f7Pd_F0oA: Video unavailable. This video contains content from UMG, who has blocked it in your country on copyright grounds
youtubeSync    | 2022-11-28T22:28:30.307483023Z ERROR: [youtube] e7b7kxzqiAo: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
youtubeSync    | 2022-11-28T22:28:31.089155563Z ERROR: [youtube] Sy1JehbNqp8: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:31.594120101Z ERROR: [youtube] _Wh1yr3ilNQ: Private video. Sign in if you've been granted access to this video
youtubeSync    | 2022-11-28T22:28:32.356627509Z ERROR: [youtube] dNiN7h5oB4k: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:33.095482424Z ERROR: [youtube] iGJ9cxrNCzo: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:33.811438126Z ERROR: [youtube] GlztXk31W6k: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:34.573018614Z ERROR: [youtube] -oFKyFNvOlo: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:35.275290747Z ERROR: [youtube] _3nUaXYaMhQ: Video unavailable. This video is not available
youtubeSync    | 2022-11-28T22:28:35.724749251Z ERROR: [youtube] s4zZ9ffWlu4: Private video. Sign in if you've been granted access to this video
youtubeSync    | 2022-11-28T22:28:36.737253407Z ERROR: [youtube] rKn4AD4vnU0: Video unavailable. This video contains content from SME, who has blocked it in your country on copyright grounds
youtubeSync    | 2022-11-28T22:28:36.812724332Z 2022-11-28 22:28:36.811 ERROR youtube_sync.download Command '['yt-dlp', '--continue', '--ignore-errors', '--rm-cache-dir', '--socket-timeout', '10', '--download-archive', '/downloads/SHAY/downloaded.txt', '-o', '/downloads/SHAY/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PL-1j3ZZT-LGc9h4v3XQif90l0H5fwGHxH', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0']' returned non-zero exit status 1.
youtubeSync    | 2022-11-28T22:28:36.812822012Z Traceback (most recent call last):
youtubeSync    | 2022-11-28T22:28:36.812828132Z   File "/bin/youtube_sync.py", line 36, in download
youtubeSync    | 2022-11-28T22:28:36.812831812Z     command_output = check_output(command)
youtubeSync    | 2022-11-28T22:28:36.812835012Z   File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
youtubeSync    | 2022-11-28T22:28:36.812838132Z     **kwargs).stdout
youtubeSync    | 2022-11-28T22:28:36.812853332Z   File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
youtubeSync    | 2022-11-28T22:28:36.812857092Z     output=stdout, stderr=stderr)
youtubeSync    | 2022-11-28T22:28:36.812860332Z subprocess.CalledProcessError: Command '['yt-dlp', '--continue', '--ignore-errors', '--rm-cache-dir', '--socket-timeout', '10', '--download-archive', '/downloads/SHAY/downloaded.txt', '-o', '/downloads/SHAY/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PL-1j3ZZT-LGc9h4v3XQif90l0H5fwGHxH', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0']' returned non-zero exit status 1.
```

This is the config I'm using for this playlist
```
- name: SHAY
  playlist_url: https://www.youtube.com/playlist?list=PL-1j3ZZT-LGc9h4v3XQif90l0H5fwGHxH
  args: --extract-audio --audio-format mp3 --audio-quality 0
```

I'm missing something or it's in fact a bug?

**Comment by u1234x1234** [comment]
yt-dlp which is used for downloading of Youtube videos returns a non-zero exit code when it is having problems with video downloading. It is expected behavior because some videos could be unavailable and it is was logged as a python traceback. But the thing is the python process will not be crashed in this case because of errors in yt-dlp subprocess as it just [catches and logs](https://github.com/u1234x1234/youtube-sync/blob/ad8bd95ac264f5c09c9dd15554fe2f4dd437edeb/youtube_sync.py#L38) underlying exceptions. And the sync should happen every day so these errors will be added to the logs each day but the sync shouldn't have stopped.

I'm not sure why it stopped.

I've updated the version of yt-dlp and pushed new docker image to dockerhub [u1234x1234/youtube-sync:1.0.13](https://hub.docker.com/r/u1234x1234/youtube-sync/tags) could you please check the new version?

I checked your playlist and it was downloaded successfully except for some unavailable videos that were logged.

**Comment by leornt** [comment]
Idk if it was some old version bug or if it's something with my server, but it seems to be fixed now, thank you so much

If I find somehting different will open a new ticket, but everything is working as expected
